server:
  port: 8779

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.4.151:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: push-service

netty-websocket:
  host: 0.0.0.0
  path: /websocket
  port: 8787
  discovery:
    serviceName: ws-service
    port: 8787

